### PR TITLE
Modify environment before calling Ruby

### PR DESCRIPTION
**Pull request by cirosantilli**
For https://github.com/gitlabhq/gitlabhq/pull/8356

### CODE REVIEW

**Comment by randx** [comment]
@cirosantilli any news on this?

**Comment by cirosantilli** [comment]
@randx sorry, I'm a bit busy. Feel free to close or try it out.

**Comment by bb-generation** [comment]
Don't know if this is still relevant, but I just tried this commit on a live 7.7 (+gitlab-shell 2.4.1) installation and it (mostly) worked.

The only problem was that there was no ./hooks/.env file initially and I got the following warnings after pushing via ssh (it still worked though):
```
remote: hooks/pre-receive: line 4: ./hooks/.env: No such file or directory
remote: hooks/update: line 4: ./hooks/.env: No such file or directory
remote: hooks/post-receive: line 4: ./hooks/.env: No such file or directory
```

After I created a ./hooks/.env file (with something like ```export PATH=/my/new/:/corrected/path``` in it), everything worked. I tested pushing via ssh and editing files via the web interface (which didn't work previously for me).

**Comment by cirosantilli** [comment]
@bb-generation did you also pull https://github.com/gitlabhq/gitlabhq/pull/8356/files ? that should create the file.

**Comment by bb-generation** [comment]
@cirosantilli No, I didn't.

But now I did (after removing the gitlab-shell/hooks/.env file) and it works perfectly. No warnings and ssh+http push works fine.

**Comment by cirosantilli** [comment]
cc @randx consider reopening

**Comment by jangrewe** [comment]
+1

**Comment by devfaz** [comment]
+1

**Comment by shusain** [comment]
+1 applied the changes here too, works for me thanks for the fix

**Pull request closed without merging**
