### PR TITLE
Allow to configure location of the secret file

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by jirutka** [comment]
@randx When do you merge this PR?

**Comment by randx** [comment]
OK why we need this?

**Comment by jirutka** [comment]
Maybe because not everyone is happy with violating [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) by placing _everything_ inside /home/git? Maybe because it’s kinda stupid to [create symlink](https://github.com/gitlabhq/gitlabhq/blob/master/config/initializers/gitlab_shell_secret_token.rb#L18) instead of just pointing to the actual location of the secret file? Or maybe because hard-coded paths are stupid thing in general? There are many reasons to make paths configurable.

**Comment by randx** [comment]
@jirutka your comment looks aggressive :smile:

**Comment by jirutka** [comment]
@randx I’m sorry for that, but your question has been kinda weird for me, like asking why we need to improve code quality or something like that.

**Comment by randx** [comment]
@jirutka I would like to avoid exploding of gitlab.yml config. Thats why I make sure change is necessary before accepting it. It was not obvious for me how you deploy GitLab and since we focus mostly on omnibus packages - it is not too much need in having all path customizable.

**Comment by jirutka** [comment]
@randx Thanks! I know about Omnibus package, but to be honest, I would never install such a thing on my system.

**Comment by randx** [comment]
@jirutka any reason why you don't like omnibus packages?

**Comment by rumpelsepp** [comment]
> any reason why you don't like omnibus packages?

Since any linux distribution provide solid package managment, there is no real advantage of using an *additional* package format. I maintain a [PKGBUILD](https://github.com/rumpelsepp/gitlab-pkgbuilds) for arch linux which can be installed easily with pacman. I see no real benefit in using omnibus, bacause I already have a rock solid package manager (I am quite sure that the same can be done with apt and yum).

**Comment by maxlazio** [comment]
apt and yum repos exist already

**Comment by rumpelsepp** [comment]
That's fine. *Personally* I would use them, rather than omnibus. :)

**Comment by jirutka** [comment]
@rumpelsepp Perhaps the worst thing about Omnibus is that it bundles even its own init system! Yo dawg…

**Comment by maxlazio** [comment]
@jirutka You can say the worst I can say the best thing about. Not everyone wants to control every single process and this enables users who cannot/want to bother with it to use GitLab without issues.

To each his own I guess!

**Comment by dosire** [comment]
@jirutka You're unlikely to convince people with your tone, please see https://github.com/thoughtbot/guides/tree/master/code-review

**Pull request merged**
